### ISSUE TITLE
09_a_complete_example.R has getNDVI function but needs addNDVI

### ISSUE THREAD

**Issue by adamkc** [csaybar/rgee-examples#1]
Need to replace:
```
# This function gets NDVI from a Landsat 8 image.
getNDVI = function(image) {
  return(image$normalizedDifference(c("B5", "B4")))
}
```
with:
```
# This function gets NDVI from Landsat 8 imagery.
addNDVI = function(image) {
  return(image$addBands(image$normalizedDifference(c("B5", "B4"))))
}
```
in the "09_a_complete_example.R" file.

Very excited for this project! Thanks for the work.

**Comment by csaybar** [comment]
Hi, @adamkc  thanks a lot for the feedback! changes were realized.

Before 15 de march we release version 1.0.0 of rgee where we will carry out important and necessary changes to the API. Please stay also tuned to rgee-examples!.

**Comment by adamkc** [comment]
Great! Looking forward to it.
