### ISSUE TITLE
Availability of Landsat data for your study area

### ISSUE THREAD

**Issue by ambarja** [csaybar/rgee-examples#3]
Hi @csaybar, recently, I was reading a book about "Remote Sensing with R" and a form traditional of obtaining images is using different platforms of internet through a specific path and row for a set Landsat Images, but always I questioned me If there is a manner of getting all the dataset of Landsat images for a specific place with a less than 10 cloud cover percentage?
Well, the answer is yes of course! And it thanks to **`rgee`**  :earth_africa:   :cat:  :nerd_face: 
Here in this link attached my [code](https://github.com/barja8/quickly_rgee/blob/master/Script/utils.R), perhaps it can be to future a function in `**rgee**` for obtaining different datasets as Sentinel, Aster, or other satellite images instead of Landsat
```css

library(rgee)
library(sf)
library(tidyverse)
source('utils.R')

ee_Initialize()

ee_search_dataset() %>% 
  ee_search_type('ImageCollection') %>% 
  ee_search_provider('USGS') %>% 
  ee_search_tags('reflectance') %>% 
  select(id)

names_id <- c('LANDSAT/LC08/C01/T1_SR',
        'LANDSAT/LT05/C01/T1_SR',
        'LANDSAT/LE07/C01/T1_SR')

lista <- img_available(id = names_id,
                       path = 4, 
                       row = 71,
                       cloud = 5)

plot_available_img(name = 'Landsat 5, 7 and 8 ',img_available = lista)
```
![](https://github.com/barja8/quickly_rgee/blob/master/Script/plot.png?raw=true)

**Comment by csaybar** [comment]
Thanks @barja8 I added it!
